name: Hello World
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16]
        environment: [development]
        
    steps:
      - name: Checkout siemens
        uses: actions/checkout@v2
      - name: Print Hello World
        id: hello_variables
        run: |
          echo '::set-output name=h_output::Hello world'
      - name: Hello World variable
        run: |
          echo '${{steps.hello_variables.outputs.h_output}}'
      
      - name: using variable
        run: |
          echo '${{secrets.USERNAME}}'
      
      
      - name: Matrix configuration
        run: |
          echo 'Operating System: ${{matrix.os}}'
          echo 'Node version: ${{matrix.node-version}}'
          echo 'Environment: ${{matrix.environment}}'
        
